#  Documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
    - -s -X main.version={{.Version}} -extldflags "-static"
  goos:
    - linux
  goarch:
    - "386"
    - "amd64"
  main: ./cmd/finance-fulfilment-archive-api-cli/main.go

archives:
- id: default
  replacements:
    linux: Linux
    386: i386
    amd64: x86_64
  format: zip
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  files:
    - none*
  wrap_in_directory: false
release:
  github:
    owner: utilitywarehouse
    name: finance-fulfilment-archive-api-cli

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
